//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsyntaxExcelAddIn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbsyntaxExcelAddIn.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absyntax Projects.
        /// </summary>
        public static string AbsyntaxProjects {
            get {
                return ResourceManager.GetString("AbsyntaxProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asynchronous.
        /// </summary>
        public static string Asynchronous {
            get {
                return ResourceManager.GetString("Asynchronous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by column.
        /// </summary>
        public static string ByCol {
            get {
                return ResourceManager.GetString("ByCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by row.
        /// </summary>
        public static string ByRow {
            get {
                return ResourceManager.GetString("ByRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Caption_Abort {
            get {
                return ResourceManager.GetString("Caption_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Caption_Cancel {
            get {
                return ResourceManager.GetString("Caption_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Caption_Close {
            get {
                return ResourceManager.GetString("Caption_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Licence.
        /// </summary>
        public static string Caption_FullLicence {
            get {
                return ResourceManager.GetString("Caption_FullLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Caption_Ok {
            get {
                return ResourceManager.GetString("Caption_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Execution Licence.
        /// </summary>
        public static string Caption_TPELicence {
            get {
                return ResourceManager.GetString("Caption_TPELicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id:.
        /// </summary>
        public static string Label_ClientId {
            get {
                return ResourceManager.GetString("Label_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Label_Configure {
            get {
                return ResourceManager.GetString("Label_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Label_Run {
            get {
                return ResourceManager.GetString("Label_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Licence.
        /// </summary>
        public static string Label_SetLicence {
            get {
                return ResourceManager.GetString("Label_SetLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Run.
        /// </summary>
        public static string LastRun {
            get {
                return ResourceManager.GetString("LastRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to abort this run?.
        /// </summary>
        public static string Msg_AbortPrompt {
            get {
                return ResourceManager.GetString("Msg_AbortPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write output data to {0}..
        /// </summary>
        public static string Msg_FailedToWriteOutputData {
            get {
                return ResourceManager.GetString("Msg_FailedToWriteOutputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [The host process is not yet open.  This may indicate an issue with your Absyntax licence.].
        /// </summary>
        public static string Msg_HostProcessNotOpen {
            get {
                return ResourceManager.GetString("Msg_HostProcessNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Please wait while the host service starts.].
        /// </summary>
        public static string Msg_HostServiceNotAvailable {
            get {
                return ResourceManager.GetString("Msg_HostServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project..
        /// </summary>
        public static string Msg_LoadingProject {
            get {
                return ResourceManager.GetString("Msg_LoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No valid, enabled projects have been defined.  Use the Configure button to create and maintain project rules.].
        /// </summary>
        public static string Msg_NoValidRules {
            get {
                return ResourceManager.GetString("Msg_NoValidRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No project path set].
        /// </summary>
        public static string ProjectPathNotSpecified {
            get {
                return ResourceManager.GetString("ProjectPathNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Absyntax Projects.
        /// </summary>
        public static string ScreenTip_Configure {
            get {
                return ResourceManager.GetString("ScreenTip_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Configured Projects.
        /// </summary>
        public static string ScreenTip_Run {
            get {
                return ResourceManager.GetString("ScreenTip_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Absyntax Licence.
        /// </summary>
        public static string ScreenTip_SetLicence {
            get {
                return ResourceManager.GetString("ScreenTip_SetLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Absyntax project configuration dialogue to maintain project invocation rules..
        /// </summary>
        public static string SuperTip_Configure {
            get {
                return ResourceManager.GetString("SuperTip_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute all configured, valid and enabled Absyntax projects..
        /// </summary>
        public static string SuperTip_Run {
            get {
                return ResourceManager.GetString("SuperTip_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a dialogue allowing you to specify which Absyntax licence to use..
        /// </summary>
        public static string SuperTip_SetLicence {
            get {
                return ResourceManager.GetString("SuperTip_SetLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronous.
        /// </summary>
        public static string Synchronous {
            get {
                return ResourceManager.GetString("Synchronous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Limit.
        /// </summary>
        public static string TimeLimit {
            get {
                return ResourceManager.GetString("TimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absyntax Licence.
        /// </summary>
        public static string Title_LicenceDialogue {
            get {
                return ResourceManager.GetString("Title_LicenceDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absyntax Project Configuration.
        /// </summary>
        public static string Title_ProjectConfigurationDialogue {
            get {
                return ResourceManager.GetString("Title_ProjectConfigurationDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absyntax Execution Coordinator.
        /// </summary>
        public static string Title_ProjectExecutionDialogue {
            get {
                return ResourceManager.GetString("Title_ProjectExecutionDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rule.
        /// </summary>
        public static string ToolTip_AddRule {
            get {
                return ResourceManager.GetString("ToolTip_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demote Rule.
        /// </summary>
        public static string ToolTip_Demote {
            get {
                return ResourceManager.GetString("ToolTip_Demote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Mode.
        /// </summary>
        public static string ToolTip_Mode {
            get {
                return ResourceManager.GetString("ToolTip_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote Rule.
        /// </summary>
        public static string ToolTip_Promote {
            get {
                return ResourceManager.GetString("ToolTip_Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rule.
        /// </summary>
        public static string ToolTip_RemoveRule {
            get {
                return ResourceManager.GetString("ToolTip_RemoveRule", resourceCulture);
            }
        }
    }
}
